"""Video saliency scoring — three variants (§4a, §4a-L6, §4a-Sim of videozip_plan.md).

All variants return per-group retention scores in [0, 1]. High score = this group is
salient = audio in this group should be compressed LESS.
"""

from __future__ import annotations

from typing import List, Optional, Sequence

import torch


def _aggregate_to_groups(
    vid_importance: torch.Tensor,
    num_input_frames: int,
    video_token_per_frame: int,
    num_groups: int,
) -> List[float]:
    """Common spatial+temporal aggregation shared by all three saliency variants."""
    N_v = num_input_frames * video_token_per_frame
    if vid_importance.numel() < N_v:
        raise ValueError(
            f"vid_importance has {vid_importance.numel()} elements but layout expects "
            f"{N_v} ({num_input_frames} frames x {video_token_per_frame} tokens/frame)."
        )
    vid_importance = vid_importance[:N_v]
    frames_x_spatial = vid_importance.reshape(num_input_frames, video_token_per_frame)
    frame_importance = frames_x_spatial.mean(dim=1)

    frames_per_group = max(1, num_input_frames // num_groups)
    group_importances: List[float] = []
    for g in range(num_groups):
        s = g * frames_per_group
        e = s + frames_per_group if g < num_groups - 1 else num_input_frames
        group_importances.append(frame_importance[s:e].mean().item())

    mx = max(group_importances) + 1e-8
    return [v / mx for v in group_importances]


def omnizip_video_saliency(
    video_feature: torch.Tensor,
    video_indices: torch.Tensor,
    attn_logits: torch.Tensor,
    num_input_frames: int,
    video_token_per_frame: int,
    num_groups: int,
) -> List[float]:
    """Live-attention video saliency. §4a of videozip_plan.md.

    Uses the same `attn_logits` channel that OmniZip already computes for its audio
    saliency, but reads it at the video token positions.
    """
    if attn_logits.dim() == 3:
        importance = attn_logits.mean(dim=0).sum(dim=0)
    else:
        importance = attn_logits.sum(dim=0)

    N_v = video_feature.shape[0]
    vid_importance = importance[video_indices[:N_v]]
    return _aggregate_to_groups(
        vid_importance, num_input_frames, video_token_per_frame, num_groups
    )


def omnizip_video_saliency_l6(
    l6_video_scores: torch.Tensor,
    num_input_frames: int,
    video_token_per_frame: int,
    num_groups: int,
) -> List[float]:
    """Cached L6 video saliency. §4a-L6 of videozip_plan.md.

    Consumes a precomputed 1D importance vector of length N_v that was generated by
    `precompute_l6_saliency.py`. The cache stores text->video Q*K cross-attention
    scores at layer 6, mean-reduced over heads and text query positions — these are
    already a per-video-token importance signal and require no further reduction.

    Use `videozip.cache.load_video_scores()` to retrieve the score vector for a given
    video, then convert it to a torch tensor before passing it here.
    """
    if l6_video_scores.dim() != 1:
        raise ValueError(
            f"l6_video_scores must be 1D (one score per video token); got shape "
            f"{tuple(l6_video_scores.shape)}."
        )
    return _aggregate_to_groups(
        l6_video_scores, num_input_frames, video_token_per_frame, num_groups
    )


def omnizip_video_saliency_simonly(
    video_feature: torch.Tensor,
    audio_feature: torch.Tensor,
    num_input_frames: int,
    video_token_per_frame: int,
    num_groups: int,
) -> List[float]:
    """Frozen cross-modal similarity saliency. §4a-Sim of videozip_plan.md.

    Aurelle's baseline: no attention logits at all. Per-video-token importance =
    max cosine similarity to any audio token. Tests whether the attention-logit channel
    actually contributes information beyond raw embedding alignment.
    """
    if audio_feature.numel() == 0:
        return [1.0 / num_groups] * num_groups
    v_norm = torch.nn.functional.normalize(video_feature, dim=-1)
    a_norm = torch.nn.functional.normalize(audio_feature, dim=-1)
    av_sim = v_norm @ a_norm.T
    vid_importance = av_sim.max(dim=1).values
    return _aggregate_to_groups(
        vid_importance, num_input_frames, video_token_per_frame, num_groups
    )


def dispatch_video_saliency(
    source: str,
    *,
    video_feature: torch.Tensor,
    video_indices: torch.Tensor,
    num_input_frames: int,
    video_token_per_frame: int,
    num_groups: int,
    attn_logits: Optional[torch.Tensor] = None,
    l6_video_scores: Optional[torch.Tensor] = None,
    audio_feature: Optional[torch.Tensor] = None,
) -> List[float]:
    """Single entry point used by the orchestrator. Selects a saliency variant by name."""
    if source == "attn":
        if attn_logits is None:
            raise ValueError("source='attn' requires attn_logits")
        return omnizip_video_saliency(
            video_feature, video_indices, attn_logits,
            num_input_frames, video_token_per_frame, num_groups,
        )
    if source == "l6_cached":
        if l6_video_scores is None:
            raise ValueError(
                "source='l6_cached' requires l6_video_scores (1D, length N_v); load it "
                "via videozip.cache.load_video_scores()"
            )
        return omnizip_video_saliency_l6(
            l6_video_scores, num_input_frames, video_token_per_frame, num_groups,
        )
    if source == "sim_only":
        if audio_feature is None:
            raise ValueError("source='sim_only' requires audio_feature")
        return omnizip_video_saliency_simonly(
            video_feature, audio_feature,
            num_input_frames, video_token_per_frame, num_groups,
        )
    raise ValueError(f"Unknown video_saliency_source: {source!r}")
